In [115]:
# import requests
# import random
# userAgents = [{"ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.10 Safari/605.1.1", "pct": 43.03}, {"ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.3", "pct": 21.05}, {"ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.3", "pct": 17.34}, {"ua": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.3", "pct": 3.72}, {"ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36 Trailer/93.3.8652.5", "pct": 2.48}, {"ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36 Edg/134.0.0.", "pct": 2.48}, {"ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.", "pct": 2.48}, {"ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36 OPR/117.0.0.", "pct": 2.48}, {"ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36 Edg/132.0.0.", "pct": 1.24}, {"ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.1958", "pct": 1.24}, {"ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.", "pct": 1.24}, {"ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.3", "pct": 1.24}]

# # Uses the supplied percentages as relative selection weights.
# selected = random.choices(
#     userAgents,
#     weights=[item["pct"] for item in userAgents],
#     k=1,
# )[0]

# url = "https://www.etsy.com/shop/3DishDesigns/sold?ref=shop_home_listings"

# try:
#     response = requests.get(
#         url,
#         headers={
#             "User-Agent": selected["ua"],
#             "Accept": "text/html,application/xhtml+xml",
#             "Accept-Language": "en-US,en;q=0.9",
#         },
#         timeout=30,
#     )

#     print("User-Agent:", selected["ua"])
#     print("HTTP status:", response.status_code)
#     print("Content-Type:", response.headers.get("Content-Type"))
#     print("Response preview:\n", response.text[:1500])

# except requests.RequestException as exc:
#     print("Request failed:", exc)

In [116]:
# # Source - https://stackoverflow.com/a/70360691
# # Posted by mediocrite
# # Retrieved 2026-09-20, License - CC BY-SA 4.0

# from bs4 import BeautifulSoup

# html = "<script type='text/javascript' src='https://www.etsy.com/assets/js/etsy_mini_shop.js'></script><script type='text/javascript'>new Etsy.Mini(FordsFoundry,'gallery',4,1,0,'https://www.etsy.com');</script>"
# soup = BeautifulSoup(html, features="html.parser")

# text = soup.get_text()
# # url_part = soup.find('a')
# # url_str = url_part['href']

# print(text)

In [117]:
# import requests
# from pathlib import Path

# url = "https://www.etsy.com/shop/3DishDesigns/sold?ref=shop_home_listings"

# response = requests.get(url, timeout=30)
# print("HTTP status:", response.status_code)

# response.raise_for_status()  # Stops here if Etsy returns 403.

# Path("sold_listings.html").write_text(
#     response.text,
#     encoding="utf-8",
# )
# print("HTML saved.")

In [118]:
# # Import libraries
# from bs4 import BeautifulSoup
# import requests

# # set the url to perform the get request
# # URL = 'https://www.geeksforgeeks.org/python/how-to-scrape-all-pdf-files-in-a-website/'
# URL = "https://www.etsy.com/shop/3DishDesigns/sold?ref=shop_home_listings"
# page = requests.get(URL)

# # load the page content
# text = page.content

# # make a soup object by using
# # beautiful soup and set the markup as html parser
# soup = BeautifulSoup(text, "html.parser")

# # open the file in w mode
# # set encoding to UTF-8
# with open("output.html", "w", encoding = 'utf-8') as file:
  
#     # prettify the soup object and convert it into a string
#     file.write(str(soup.prettify()))

In [119]:

# import requests                                                                            

# r = requests.get('https://www.etsy.com/shop/3DishDesigns/sold?ref=shop_home_listings')    
# print(r.content)
# # with open('out.html', 'w') as f:
# #     f.write(r.content)

In [120]:
# import requests
# import urllib.parse
# from bs4 import BeautifulSoup
# import json
# import re

# # Configuration
# token = "<your-token>"
# product_url = "https://www.etsy.com/listing/4306368113/birth-flower-ring-925-sterling-silver"

# # Make API request
# encoded_url = urllib.parse.quote_plus(product_url)
# api_url = f"https://api.scrape.do?token={token}&url={encoded_url}&geoCode=us&super=true&extraHeaders=true"
# headers = {"sd-x-detected-locale": "USD|en-US|US"}
# response = requests.get(api_url, headers=headers)

# soup = BeautifulSoup(response.text, "html.parser")

# # Initialize product data
# product = {"url": product_url}

# # Extract listing ID from URL
# listing_match = re.search(r"/listing/(\d+)", product_url)
# if listing_match:
#     product["listing_id"] = listing_match.group(1)

# # Extract JSON-LD structured data
# for script in soup.find_all("script", attrs={"type": "application/ld+json"}):
#     try:
#         data = json.loads(script.string)
#         objs = data if isinstance(data, list) else [data]

#         for obj in objs:
#             product_type = obj.get("@type")
#             if product_type == "Product" or (isinstance(product_type, list) and "Product" in product_type):
#                 # Extract basic info
#                 product["name"] = obj.get("name")
#                 product["description"] = obj.get("description")
#                 product["category"] = obj.get("category")

#                 # Extract shop/brand
#                 brand = obj.get("brand")
#                 if isinstance(brand, dict):
#                     product["shop"] = brand.get("name")
#                 elif isinstance(brand, str):
#                     product["shop"] = brand

#                 # Extract images
#                 image_data = obj.get("image")
#                 if isinstance(image_data, list):
#                     product["images"] = image_data
#                 elif image_data:
#                     product["images"] = [image_data]
#                 else:
#                     product["images"] = []

#                 # Extract price from offers
#                 offers = obj.get("offers")
#                 if isinstance(offers, list):
#                     offers = offers[0] if offers else {}

#                 price = (offers or {}).get("price") or (offers or {}).get("lowPrice")
#                 product["price"] = float(price) if price else None
#                 product["currency"] = (offers or {}).get("priceCurrency")

#                 # Extract availability
#                 avail = (offers or {}).get("availability") or ""
#                 if "/" in avail:
#                     product["availability"] = avail.split("/")[-1]
#                 elif avail:
#                     product["availability"] = avail

#                 # Extract rating
#                 agg = obj.get("aggregateRating") or {}
#                 product["rating"] = agg.get("ratingValue")
#                 product["review_count"] = agg.get("reviewCount")
#                 break
#     except:
#         continue

# # Print results
# print(json.dumps(product, indent=2, sort_keys=True))

In [121]:
%pip -q install beautifulsoup4 pandas

from pathlib import Path
import re
import warnings

import pandas as pd
from bs4 import BeautifulSoup
from IPython.display import display

Note: you may need to restart the kernel to use updated packages.

In [122]:



def parse_saved_etsy_pages(folder="etsy_pages"):
    folder = Path(folder)
    files = sorted(
        p for p in folder.glob("*")
        if p.suffix.lower() in {".html", ".htm", ".txt"}
    )
    if not files:
        raise FileNotFoundError(f"No saved pages found in {folder.resolve()}")

    rows = []

    for path in files:
        soup = BeautifulSoup(path.read_bytes(), "html.parser")

        # Matches the actual card structure in your supplied HTML.
        cards = soup.select("[data-listing-card-v2][data-listing-id]")

        if not cards:
            warnings.warn(f"{path.name}: no listing cards found.")
            continue

        count = 0
        for card in cards:
            link = card.select_one('a.listing-link[href*="/listing/"]')
            if link is None:
                continue

            match = re.search(r"/listing/(\d+)", link["href"])
            if not match:
                continue

            heading = card.select_one("h3.v2-listing-card__title")
            image = card.select_one("img")
            price_area = card.select_one(".n-listing-card__price")
            price_text = (
                price_area.get_text(" ", strip=True) if price_area else ""
            )

            # Only include cards explicitly marked as sold.
            if not re.search(r"\bsold(?:\s+out)?\b", price_text, re.I):
                continue

            price = (
                price_area.select_one(".currency-value")
                if price_area else None
            )
            currency = (
                price_area.select_one(".currency-symbol")
                if price_area else None
            )

            rows.append({
                "listing_id": match.group(1),
                "shop_id": card.get("data-shop-id"),
                "title": (
                    link.get("title")
                    or (heading.get_text(" ", strip=True) if heading else None)
                    or (image.get("alt") if image else None)
                ),
                "status": price_text,
                "displayed_price": (
                    price.get_text(strip=True) if price else None
                ),
                "currency_symbol": (
                    currency.get_text(strip=True) if currency else None
                ),
                "listing_url": f"https://www.etsy.com/listing/{match.group(1)}",
                "image_url": (
                    image.get("data-src") or image.get("src")
                    if image else None
                ),
                "source_file": path.name,
            })
            count += 1

        # print(f"{path.name}: {count} sold cards")

    if not rows:
        raise RuntimeError("No cards explicitly marked Sold were found.")

    return pd.DataFrame(rows).convert_dtypes()





# Optional:
# summary_df.to_csv("sold_listing_summary.csv", index=False)

In [123]:
print("3DishDesigns")
df_3DishDesigns = parse_saved_etsy_pages("etsy_pages/3DishDesigns")
summary_df_3DishDesigns = (
    df_3DishDesigns.groupby("listing_id", as_index=False)
      .agg(
          name=("title", "first"),
          times_observed=("listing_id", "size"),
      )
      .sort_values("times_observed", ascending=False)
      [["name", "times_observed"]]
      .reset_index(drop=True)
)

# with pd.option_context(
#     "display.max_rows", None,
#     "display.max_columns", None,
#     "display.max_colwidth", None,
# ):
#     display(summary_df_3DishDesigns)
summary_df_3DishDesigns.head(50)

3DishDesigns

                                                 name  times_observed
0   Leaves From The Vine - Magnetic Commander Show...              75
1   Y'shtola, Knight's Blessed - Magnetic Commande...              75
2   Hydra Theme - Magnetic Commander Showcase Deck...              57
3   Bunny Theme - Magnetic Commander Showcase Deck...              56
4     Y'shtola - Magnetic Commander Showcase Deck Box              49
5   Final Fantasy 7 Battle Menu - Magnetic Command...              45
6   Kaalia of the Vast - Magnetic Commander Showca...              42
7   Karlach, Fury of Avernus - Magnetic Commander ...              39
8   Shroofus Sproutsire - Magnetic Commander Showc...              38
9             MTG EDH Slim Profile Commander Deck Box              37
10  Bria, Riptide Rogue / Otter Theme - Magnetic C...              33
11  Godzilla, King of the Monsters - Magnetic Comm...              33
12  Nekusar, the Mindrazer - Magnetic Commander Sh...              31
13  Squirrel Theme - Magnetic Commander Showcase D...              30
14  Lathril, Blade of the Elves - Magnetic Command...              29
15  The Wise Mothman - Magnetic Commander Showcase...              28
16  Rin and Seri, Inseparable - Magnetic Commander...              27
17    Deadpool - Magnetic Commander Showcase Deck Box              26
18   Cat Theme - Magnetic Commander Showcase Deck Box              26
19  Tifa Lockhart - Magnetic Commander Showcase De...              24
20  Final Fantasy Hero's - Magnetic Commander Show...              24
21  Pantlaza, Sun-Favored - Magnetic Commander Sho...              20
22  Rendmaw, Creaking Nest - Magnetic Commander Sh...              20
23  Wanted Earth Bender - Magnetic Commander Showc...              18
24  Firebending Uncle - Magnetic Commander Showcas...              18
25  Chibi Y'shtola - Magnetic Commander Showcase D...              17
26  Gojo, the Strongest - Magnetic Commander Showc...              16
27       Cloud - Magnetic Commander Showcase Deck Box              16
28        Tifa - Magnetic Commander Showcase Deck Box              16
29  Bello, Bard of the Brambles - Magnetic Command...              16
30  Golden Chocobo - Magnetic Commander Showcase D...              15
31  Sliver Hivelord - Magnetic Commander Showcase ...              15
32  Emet-Selch - Magnetic Commander Showcase Deck Box              14
33  Shadowheart, Dark Justiciar - Magnetic Command...              14
34  Alela, Artful Provocateur - Magnetic Commander...              13
35    Lucky 38 - Magnetic Commander Showcase Deck Box              13
36  Queen Marchesa - Magnetic Commander Showcase D...              12
37  Tasha, the Witch Queen - Magnetic Commander Sh...              12
38      Ragost - Magnetic Commander Showcase Deck Box              12
39  The Jolly Balloon Man - Magnetic Commander Sho...              12
40  High Perfect Morcant - Magnetic Commander Show...              11
41  Edgar Markov - Magnetic Commander Showcase Dec...              11
42        Urza - Magnetic Commander Showcase Deck Box              11
43         Teysa Karlov - Magnetic Commander Deck Box              10
44  Liesa, Shroud of Dusk - Magnetic Commander Sho...              10
45  Kibo, Uktabi Prince - Magnetic Commander Showc...              10
46  Tom Bombadil - Magnetic Commander Showcase Dec...              10
47  Meren of Clan Nel Toth - Magnetic Commander Sh...              10
48  G'raha Tia - Magnetic Commander Showcase Deck Box              10
49  Sephiroth One-Winged Angel - Magnetic Commande...               9

In [126]:
print("GroovadelicGallery")
df_GroovadelicGallery = parse_saved_etsy_pages("etsy_pages/GroovadelicGallery")
summary_df_GroovadelicGallery = (
    df_GroovadelicGallery.groupby("listing_id", as_index=False)
      .agg(
          name=("title", "first"),
          times_observed=("listing_id", "size"),
      )
      .sort_values("times_observed", ascending=False)
      [["name", "times_observed"]]
      .reset_index(drop=True)
)

# with pd.option_context(
#     "display.max_rows", None,
#     "display.max_columns", None,
#     "display.max_colwidth", None,
# ):
#     display(summary_df_GroovadelicGallery)
summary_df_GroovadelicGallery.head(50)

GroovadelicGallery

                                                 name  times_observed
0   Vaporwave Floral Shoppe Macintosh Plus Helios ...              24
1                      Vaporwave Helios Stud Earrings              15
2                                Garden Toad Earrings              13
3   Magic the Gathering Commander Deck Box Carrot ...              13
4                           Vaporwave Helios Earrings              11
5   Magic the Gathering Commander Deck Box Barad-d...               9
6   Magic the Gathering Commander Deck Box Mushroo...               9
7   Magic the Gathering Commander Deck Box Eriette...               7
8   Magic the Gathering Commander Deck Box Edgar M...               7
9   Magic the Gathering Commander Deck Box Trash C...               7
10  Magic the Gathering Commander Deck Box Biblica...               6
11                                 Yoga Frog Earrings               5
12  MTG Deck Box: 3D Printed Commander Card Storag...               5
13  Magic the Gathering Commander Deck Box Iron Ma...               4
14  Magic the Gathering Commander Deck Box Eriette...               4
15  Magic the Gathering Commander Deck Box Krenko ...               4
16                               Garden Toad Necklace               4
17                             Venus de Milo Earrings               3
18  Magic the Gathering Commander Deck Box Parthen...               3
19                          Vaporwave Helios Necklace               3
20                        David Michelangelo Earrings               3
21                       Venus of Willendorf Necklace               3
22                             Venus de Milo Necklace               3
23  Magic the Gathering Commander Deck Box Slime O...               3
24                                       Atlas Statue               2
25                       Hypnos God of Sleep Earrings               2
26                       Venus of Willendorf Earrings               2
27  Smiling Friends Headquarters Adult Swim Critte...               2
28                             Leonardo da Vinci Bust               2
29  Magic the Gathering Commander Deck Box Christm...               2
30                          Vaporwave Helios Keychain               2
31  Magic the Gathering Commander Deck Box Univers...               2
32                              Lilypad Toad Keychain               2
33                         Leonardo da Vinci Necklace               1
34        The Thinker Rodin Scanned 3D Printed Statue               1
35                         Leonardo da Vinci Earrings               1
36                                     Atlas Keychain               1
37                                   Yoga Frog Statue               1
38                            Goddess Athena Necklace               1
39                              Ancient Mars Keychain               1
40                                 Yoga Frog Necklace               1
41                           Ares God of War Necklace               1
42                                  Ancient Mars Bust               1
43                              Ancient Mars Necklace               1
44                       Hypnos God of Sleep Keychain               1
45                       Hypnos God of Sleep Necklace               1
46                             Venus de Milo Keychain               1
47                           Ares God of War Earrings               1
48                                        Garden Toad               1
49                           Hypnos God of Sleep Bust               1

In [125]:
print("FableForgedWorkshop")
df_FableForgedWorkshop = parse_saved_etsy_pages("etsy_pages/FableForgedWorkshop")
summary_df_FableForgedWorkshop = (
    df_FableForgedWorkshop.groupby("listing_id", as_index=False)
      .agg(
          name=("title", "first"),
          times_observed=("listing_id", "size"),
      )
      .sort_values("times_observed", ascending=False)
      [["name", "times_observed"]]
      .reset_index(drop=True)
)

with pd.option_context(
    "display.max_rows", None,
    "display.max_columns", None,
    "display.max_colwidth", None,
):
    display(summary_df_FableForgedWorkshop)

FableForgedWorkshop

,name,times_observed
0,MTG Trashcan Raccoon Deck Box for 100 Cards | Magic the Gathering | EDH | Fable Forged Workshop,1600
1,Mini Nuke MTG Deck Box: Fallout Themed 100 Card Storage,624
2,"Buster Sword MTG Deck Box: Final Fantasy Inspired, EDH 100 Card",477
3,MTG Commander Tray | Magic the Gathering | Command Zone Organizer | 3D Printed | Fable Forged Workshop,455
4,MTG Squirrel Deck Box | Magic the Gathering | EDH | 100 Card | Fable Forged Workshop,394
5,MTG Life Counter | D100 | Custom Made | 3D Printed | Commander Tray Compatible | Fable Forged Workshop,146
6,MTG First Sliver Deck Box: 100 Card EDH Commander,124
7,MTG Edgar Markov Vampire Deck Box | Magic the Gathering | EDH | 100 Card | Fable Forged Workshop,118
8,MTG Mouse Deck Box | Magic the Gathering | EDH | 100 Card | Fable Forged Workshop,116
9,MTG Dragon Deck Box | EDH | Magic the Gathering | 100 Cards | Some Assembly Required - Glue included!,113
10,MTG Commander Tray Version 2: 3D Printed Command Zone Organizer,111
11,MTG Angel Deck Box | Magic the Gathering | EDH | 100 Card | Fable Forged Workshop,106
12,MTG Dino Tribal Commander Deck Box | Magic the Gathering | EDH | 100 Card | Fable Forged Workshop,93
13,MTG Trashcan Rat Deck Box for 100 Cards | Magic the Gathering | EDH | Fable Forged Workshop,91
14,MTG Avatar Deck Box | Magic the Gathering | EDH | 100 Card | Fable Forged Workshop,88
15,MTG Krenko Goblin Deck Box | Magic the Gathering | EDH | 100 Card | Fable Forged Workshop,84
16,MTG Vampire Coffin Deck Box | Magic the Gathering | EDH | 100 Cards | Fable Forged Workshop,82
17,MTG Cat Deck Box | Magic the Gathering | EDH | 100 Card | Fable Forged Workshop,78
18,"MTG Barrel Deck Box: Thunder Junction, EDH, 100-Card Capacity",77
19,Minas Tirith MTG Deck Box | LOTR Magic the Gathering 100 Card EDH,74
20,MTG Haunted House Deck Box | Magic the Gathering | EDH | 100 Card | Fable Forged Workshop,72
21,MTG Eldrazi Deck Box | Magic the Gathering | EDH | 100 Card | Fable Forged Workshop,64
22,MTG Necromonicon | Magic the Gathering | EDH | 100 Card | Fable Forged Workshop,63
23,MTG Parthenon Deck Box | EDH | Magic the Gathering | 100 Box | Fable Forged Workshop,58
24,"Duskmourn MTG VHS Deck Box: 100 Card EDH, Customizable",57
25,MTG Deathpool Deck Box for 100 Cards | Magic the Gathering | EDH | Fable Forged Workshop,56
26,MTG Chocobo Egg Deck Box for 100 Cards | Magic the Gathering | EDH | Fable Forged Workshop,56
27,MTG LOTR Sauron’s Tower Inspired Deck Box | Magic the Gathering | EDH | 100 Card | Fable Forged Workshop,56
28,MTG Apple of Eden Deck Box | EDH | Magic the Gathering | 100 Card | Fable Forged Workshop,55
29,"Pumpkin Bomb MTG Deck Box: Final Fantasy Inspired, EDH 100 Card",47
30,MTG Spongebob Inspired Pineapple House Deck Box | Magic the Gathering | EDH | 100 Card | Fable Forged Workshop,38
31,MTG Steel Man Deck Box | Magic the Gathering | EDH | 100 Card | Fable Forged Workshop,35
32,MTG Zombie Commander Deck Box | Magic the Gathering | EDH | 100 Card | Fable Forged Workshop,34
33,MTG Haystack Deck Box | Magic the Gathering | EDH | 100 Card | Fable Forged Workshop,30
34,MTG Moogle Deck Box for 100 Cards | Magic the Gathering | EDH | Fable Forged Workshop,27
35,MTG Witch Cauldron Deck Box | Magic the Gathering | EDH | 100 Card | Fable Forged Workshop,26
36,MTG LOTR Hobbit Hole Inspired Deck Box | Magic the Gathering | EDH | 100 Card | Fable Forged Workshop,22
37,MTG Knight Templar Helmet Deck Box | EDH | Magic the Gathering | 100 Card | Fable Forged Workshop,21
38,MTG Rabbit Deck Box | Magic the Gathering | EDH | 100 Card | Fable Forged Workshop,19
39,MTG Wolf Man Deck Box | Magic the Gathering | EDH | 100 Card | Fable Forged Workshop,19
40,MTG Superhero Tower Deck Box | Magic the Gathering | EDH | 100 Card | Fable Forged Workshop,18
41,MTG Planeswalker Gauntlet Deck Box Inspired | Magic the Gathering | EDH | 100 Card | Fable Forged Workshop,17
42,Sliver Thrumming Hivepool MTG Deck Box: EDH 100 Card,16
43,MTG Shark Deck Box | 100 Card | Commander,12
44,Venom MTG Deck Box: EDH 100 Card,12
45,MTG Turtle Shell Deck Box for 100 Cards | Magic the Gathering | EDH | Fable Forged Workshop,10
46,Deluxe Can Holding Dice Towers,9
47,MTG Otter Deck Box | Magic the Gathering | EDH | 100 Card | Fable Forged Workshop,9
48,MTG LOTR Book Deck Box for 100 Cards | Magic the Gathering | EDH | Fable Forged Workshop,8
49,MTG Theros Spartan Deck Box | Magic the Gathering | EDH | 100 Card | Fable Forged Workshop,7
50,Dice Dagger | Storage for 2 Sets of Standard Dice | 1 Set of Dice Included! | Tabletop Roleplaying Game Enthusiasts | Fable Forged Workshop,4
51,MTG Castle Keep Deck Box: EDH 100 Card,4
52,MTG Shredder Deck Box for 100 Cards | Magic the Gathering | EDH | Fable Forged Workshop,3
53,Tabletop Terrain - Giant Dark Fortress - Warhammer - Dungeons and Dragons - Roleplaying - Castle,1
54,Wizard Dice Tower,1
55,Shipping replacement,1